### PR TITLE
Proposed format updates

### PR DESCRIPTION
**Pull request by benge-lels**
- Removes `valid_humidity`, `valid_temp`. Can we accomplish the same thing by filtering the values at the reporting level?

- Adds `device_id` and `device_model` so that we can filter by individual device or type of device.

- Changes `temperature` to `temp` and `humidity` to `rh`

- Adds `lux`; This was missing

### CODE REVIEW

**Comment by benge-lels** [comment]
@TimSpence some proposed updates, let me know what you think.

**Comment by TimSpence** [comment]
Sure, the filtering can be done at either level.  The advantage of filtering before storage is that it's indexable.  Otherwise each query does a partial table scan.

**Comment by TimSpence** [comment]
+1 on the naming changes.

**Comment by benge-lels** [comment]
@TimSpence added em back, but changed `valid_humidity` to `valid_rh` to be consistent w/ the `rh` field.

**Pull request merged**
